
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ks-devops
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - podtemplates
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - appprojects
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - cluster.kubesphere.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - addonStrategies
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - addons
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - addonstrategies
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - clustersteptemplates
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - devopsprojects
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelineruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasercontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - s2ibinaries
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - s2ibuilders
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - s2ibuildertemplates
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - s2iruns
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - devops.kubesphere.io
  resources:
  - webhooks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.kubesphere.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - gitops.kubesphere.io
  resources:
  - applications/status
  verbs:
  - get
  - update
- apiGroups:
  - gitops.kubesphere.io
  resources:
  - imageupdaters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts
  verbs:
  - create
  - get
  - list
  - watch
