name: Build for E2E testing
description: Build APIServer, Controller Manager and Tools for E2E testing.

runs:
  using: "composite"
  steps:
    - name: Build Docker images for Controller Manager
      uses: docker/build-push-action@v2.4.0
      with:
        file: config/dockerfiles/controller-manager/Dockerfile
        tags: kubespheredev/devops-controller:e2e
        push: false

    - name: Build Docker images for APIServer
      uses: docker/build-push-action@v2.4.0
      with:
        file: config/dockerfiles/apiserver/Dockerfile
        tags: kubespheredev/devops-apiserver:e2e
        push: false

    - name: Build Docker images for Tools
      uses: docker/build-push-action@v2.4.0
      with:
        file: config/dockerfiles/tools/Dockerfile
        tags: kubespheredev/devops-tools:e2e
        push: false
