apiVersion: gitops.kubesphere.io/v1alpha1
kind: Application
metadata:
  name: app
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/linuxsuren-bot/open-podcasts-ui
spec:
  argoApp:
    spec:
      project: testddmtg
      source:
        repoURL: https://github.com/linuxsuren-bot/open-podcasts/
        targetRevision: HEAD
        path: config/default
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
