apiVersion: gitops.kubesphere.io/v1alpha1
kind: Application
metadata:
  name: chengleqi-test-helm
  namespace: my-devops-projecthmhx2
  labels:
    gitops.kubesphere.io/save-helm-template: "true"
spec:
  kind: fluxcd
  fluxApp:
    spec:
      source:
        sourceRef:
          kind: GitRepository
          name: fluxcd-github-repo
          namespace: my-devops-projecthmhx2
      config:
        helmRelease:
          chart:
            interval: 5m0s
            chart: ./helm-chart
            version: "0.1.0"
            valuesFiles:
              - ./helm-chart/values.yaml
              - ./helm-chart/aliyun-values.yaml
            reconcileStrategy: Revision
          template:
          deploy:
            - destination:
                # host cluster
                kubeConfig:
                targetNamespace: helm-app
              interval: 1m0s
              upgrade:
                remediation:
                  remediateLastFailure: true
                force: true
              install:
                createNamespace: true
            - destination:
                # member cluster
                kubeConfig:
                  secretRef:
                    name: node-1
                    key: value
                targetNamespace: helm-app
              # StorageNamespace used for the Helm storage.
              # Defaults to the namespace of the HelmRelease.
              storageNamespace: default
              interval: 1m0s
              upgrade:
                remediation:
                  remediateLastFailure: true
                force: true
              install:
                createNamespace: true