apiVersion: gitops.kubesphere.io/v1alpha1
kind: ImageUpdater
metadata:
  name: updater
  namespace: testddmtg
spec:
  # default value of kind is argocd
#  kind: argocd
  images:
    - ghcr.io/linuxsuren-bot/open-podcasts-ui
    - nginx
    - alpine
  argo:
    app:
      name: app
