name: Check

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "docs/**"
      - ".devcontainer/**"
      - "*.ya?ml" # ignore all yaml files(with suffix yaml or yml) in the root of the repository
      - "!codecov.yml"
      - "!.golangci.yml"
      - "!config/**"
      - "OWNERS"
      - "PROJECT"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "docs/**"
      - ".devcontainer/**"
      - "*.ya?ml" # ignore all yaml files(with suffix yaml or yml) in the root of the repository
      - "!codecov.yml"
      - "!.golangci.yml"
      - "!config/**"
      - "OWNERS"
      - "PROJECT"
  release:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      # See also https://github.com/GoogleCloudPlatform/golang-samples/blob/78dfa41f10b449ba7a06d9793cbd81878d44a4fb/.github/workflows/go.yaml#L29-L53
      - name: Run go mod tidy on root modules
        run: go mod tidy
      # If there are any diffs from goimports or go mod tidy, fail.
      - name: Verify no changes from goimports and go mod tidy.
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo 'To fix this check, run "go mod tidy"'
            git status # Show the files that failed to pass the check.
            exit 1
          fi
      - name: golint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.41.1
          skip-cache: true

  UnitTest:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
      - name: Test
        run: |
          make test
