name: E2E - Chart Install

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "docs/**"
      - ".devcontainer/**"
      - "*.ya?ml" # ignore all yaml files(with suffix yaml or yml) in the root of the repository
      - "!codecov.yml"
      - "!.golangci.yml"
      - "!config/**"
      - "OWNERS"
      - "PROJECT"

jobs:
  Install:
    name: Chart Install
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        k8sVersion: ["1.19", "1.20", "1.21", "1.22", "1.23"]
    steps:
      - uses: actions/checkout@v2

      - name: Run E2E testing
        uses: ./.github/e2e
        env:
          K8S_VERSION: ${{ matrix.k8sVersion }}
        with:
          config-file: chart-install/e2e.yaml

      - name: Upload E2E Log
        uses: actions/upload-artifact@v2
        if: ${{ failure() }} # Only upload the artifact when E2E testing failure
        with:
          name: e2e-log
          path: "${{ env.SW_INFRA_E2E_LOG_DIR }}" # The SkyWalking Infra E2E action sets SW_INFRA_E2E_LOG_DIR automatically.
